spring:
  output:
    ansi:
      enabled: never
     
logging:
  level:
    org.springframework.boot: info
       
server:
  port: 8080
  servlet:
    context-path: /FCBAPI
    encoding:
      enabled: true
      charset: UTF-8
      force: true

